apiVersion: v1
kind: Secret
metadata:
  name: postgresql-backend-go-service1-secret
  labels:
    {{- include "demo.labels" . | nindent 4 }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.postgresql.users.backendGoService1.username }}
  password: {{ .Values.postgresql.users.backendGoService1.password }}
