apiVersion: v1
kind: Service
metadata:
  name: {{ list (include "demo.backend.go.service1.name" .) "service" | join "-" }}
  labels:
    {{- include "demo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.go.service1.service.type }}
  ports:
    - port: {{ .Values.backend.go.service1.service.port }}
      targetPort: {{ .Values.backend.go.service1.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "demo.selectorLabels" . | nindent 4 }}
