{{- if .Values.backend.go.service1.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ list (include "demo.backend.go.service1.name" .) "service-account" | join "-" }}
  labels:
    {{- include "demo.labels" . | nindent 4 }}
  {{- with .Values.backend.go.service1.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.backend.go.service1.serviceAccount.automount }}
{{- end }}
