{{- if .Values.backend.go.service1.vault.create -}}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: {{ list (include "demo.backend.go.service1.name" .) "vault-auth" | join "-" }}
  labels:
    {{- include "demo.labels" . | nindent 4 }}
spec:
  method: kubernetes
  mount: {{ .Values.backend.go.service1.vault.auth.mount }}
  kubernetes:
    role: {{ list .Release.Name (include "demo.backend.go.service1.name" .) "role" | join "-" }}
    serviceAccount: {{ list (include "demo.backend.go.service1.name" .) "service-account" | join "-" }}
    audiences:
      - vault
{{- end }}
