{{- if .Values.backend.go.service1.vault.create -}}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ list (include "demo.backend.go.service1.name" .) "vault-static-secret" | join "-" }}
  labels:
    {{- include "demo.labels" . | nindent 4 }}
spec:
  type: kv-v2
  mount: {{ .Values.backend.go.service1.vault.secrets.mount }}
  path: backend/go/service1/postgresql

  destination:
    name: {{ list (include "demo.backend.go.service1.name" .) "vault-static-secret" | join "-" }}
    create: true

  refreshAfter: {{ .Values.backend.go.service1.vault.secrets.refreshAfter }}

  vaultAuthRef: {{ list (include "demo.backend.go.service1.name" .) "vault-auth" | join "-" }}
{{- end }}
