apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql
  labels:
    {{- include "demo.labels" . | nindent 4 }}
spec:
  imageName: "ghcr.io/cloudnative-pg/postgresql:{{ .Values.postgresql.version }}"

  instances: {{ .Values.postgresql.instances }}
  
  {{- with .Values.postgresql.bootstrap }}
  bootstrap:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  storage:
    size: {{ .Values.postgresql.storage.size }}
