apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: postgresql
  labels:
    {{- include "demo.labels" . | nindent 4 }}
spec:
  teamId: {{ .Values.postgresql.team }}
  postgresql:
    version: {{ .Values.postgresql.version | quote }}
  numberOfInstances: {{ .Values.postgresql.instances }}
  {{- with .Values.postgresql.storage }}
  volume:
    size: {{ . }}
  {{- end }}

  {{- with .Values.postgresql.users }}
  users:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.postgresql.databases }}
  databases:
    {{- toYaml . | nindent 4 }}
  {{- end }}
