apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql
  labels:
    {{- include "demo.labels" . | nindent 4 }}
spec:
  imageName: "ghcr.io/cloudnative-pg/postgresql:{{ .Values.postgresql.version }}"

  instances: {{ .Values.postgresql.instances }}
  
  enableSuperuserAccess: true
  # superuserSecret:
  #   name: postgresql-postgres-secret
    
  bootstrap:
    initdb:
      postInitSQL:
        - CREATE DATABASE backend_go_service1

  storage:
    size: {{ .Values.postgresql.storage.size }}
