apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: {{ .Values.database.name }}-postgresql
  labels:
    {{- include "demo.labels" . | nindent 4 }}
spec:
  teamId: {{ .Values.database.team }}
  postgresql:
    version: {{ quote .Values.database.version }}
  numberOfInstances: {{ .Values.database.instances }}
  {{- with .Values.database.storage }}
  volume:
    size: {{ . }}
  {{- end }}

  {{- with .Values.database.users }}
  users:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.database.databases }}
  databases:
    {{- toYaml . | nindent 4 }}
  {{- end }}
