{{- if .Values.vault.create -}}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: {{ include "demo.fullname" . }}
  labels:
    {{- include "demo.labels" . | nindent 4 }}
spec:
  method: kubernetes
  mount: {{ .Values.vault.auth.mount }}
  kubernetes:
    role: {{ .Values.vault.auth.role }}
    serviceAccount: {{ include "demo.serviceAccountName" . }}
    audiences:
      - vault
{{- end }}
